name: ROS2 Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04  # Ubuntu 22.04 pour ROS2 Humble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ROS2 APT repository
        run: |
          sudo apt update && sudo apt install -y curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update

      - name: Install ROS2 and Colcon
        run: |
          sudo apt install -y ros-humble-ros-base \
                              ros-humble-tf-transformations \
                              ros-humble-cv-bridge \
                              python3-colcon-common-extensions \
                              python3-pip \
                              python3-rosdep
          sudo rosdep init || true
          rosdep update



      - name: Install workspace dependencies
        run: |
          source /opt/ros/humble/setup.bash
          rosdep install --from-paths src --ignore-src -r -y

      - name: Install Python requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_direct+

      - name: Run Python tests
        run: |
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          cd src
          pytest --maxfail=1 --disable-warnings --exitfirst --verbose --timeout=30
