name: ROS2 Python Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ROS2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble  

      - name: Install ROS2 & Python tools
        run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_direct+

      - name: Run Python tests
        run: |
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          cd src
          pytest --maxfail=1 --disable-warnings --exitfirst --verbose
